behaviors:
  3DBall:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    output_path: default
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 1000
    summary_freq: 12000
    threaded: true

parameter_randomization:
  resampling-interval: 5000000
  min_mass:
    sampler-type: uniform
    min_value: 0.5
    max_value: 0.5
  max_mass:
    sampler-type: uniform
    min_value: 10
    max_value: 10
  min_scale:
    sampler-type: uniform
    min_value: 0.75
    max_value: 0.75
  max_scale:
    sampler-type: uniform
    min_value: 3
    max_value: 3
  gravity:
    sampler-type: uniform
    min_value: 7
    max_value: 12
