behaviors:
  3DBallHard:
    trainer_type: sac_transfer
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: linear
      batch_size: 256
      buffer_size: 50000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 10.0
      encoder_layers: 1
      policy_layers: 1
      forward_layers: 1
      value_layers: 1
      feature_size: 16
      separate_value_net: true
      reuse_encoder: false
      in_epoch_alter: false
      in_batch_alter: true
      use_op_buffer: false
      use_var_predict: true
      with_prior: false
      predict_return: true
      use_bisim: false
    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 1000
    summary_freq: 12000
    threaded: true
