Tennis:
  measure: progress
  thresholds: [0.02, 0.04, 0.06, 0.08, 0.1, 0.12, 0.14, 0.16, 0.18, 0.2]
  min_lesson_length: 100
  signal_smoothing: true
  parameters:
    ball_touch: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.0]
